create user deppoc identified by deppoc1 default tablespace siebel_tables profile celcom_app_profile;
grant connect to deppoc;
grant resource to deppoc;
grant select any table to deppoc;
grant select any dictionary to deppoc;

CREATE TABLE DEP_CUST_PROFILE (
  CUSTOMERROWID VARCHAR2(60), --1-6X0K7</cel:Column>
  CUSTOMERID VARCHAR2(200), --E4985522F</cel:Column>
  CUSTOMERIDTYPE VARCHAR2(120), --Passport</cel:Column>
  KENANACCOUNTID VARCHAR2(120), --
  BILLINGPROFILEID VARCHAR2(60), --
  MASTERACCOUNTNUMBER VARCHAR2(120), --
	DATEOFBIRTH DATE, --1972-01-01T00:00:00.000+07:30</cel:Column>
  GENDER VARCHAR2(120), --Male</cel:Column>
  MOTHERMAIDENNAME VARCHAR2(240), --NA</cel:Column>
  NAME VARCHAR2(400), --THEVEN NAIDU</cel:Column>
  NATIONALITY VARCHAR2(120), --"/>
  RACE VARCHAR2(120), --"/>
  SALUTATION VARCHAR2(120), --Mr</cel:Column>
  SEGMENTCODE VARCHAR2(120), --"/>
  SEGMENTGROUP VARCHAR2(120), --Consumer</cel:Column>
	SEGMENTSUBGROUP VARCHAR2(120), --Retail</cel:Column>
  TYPE VARCHAR2(120), --"/>
  VIPCODE VARCHAR2(120), --"/>
  CREDITTREATMENTCODE VARCHAR2(120), --"/>
  ASSETBILLINGACCOUNTROWID VARCHAR2(60), --"/>
  BILLINGACCOUNTSTATUS VARCHAR2(120), --"/>
  BILLINGTYPE VARCHAR2(120), --"/> BRIEFING LAYOUT
  PROMOTIONID VARCHAR2(60), --"/> ASSET PROMOTION ID
  PRIN_SUP_INDICATOR VARCHAR2(88), --"/> PROD_INT.X_VALIDATION_FLD
  ASSETIMEI VARCHAR2(400), --"/> ASSET SERIAL NUM
  ASSETMODEL VARCHAR2(1000), --"/> ASSET_XA CHAR_VAL ATTR_NAME=MODEL
  PRODUCT VARCHAR2(400), --"/> PROD_INT NAME
  PRODUCTTYPE VARCHAR2(120), --"/> PROD_INT TYPE
  PLANSEGMENTTYPE VARCHAR2(120), --"/> PROD_INT FABRIC_CD
  BUILDINGNAME VARCHAR2(400), --Somerset</cel:Column> S_ADDR_PER.X_BUILDING
  CITY VARCHAR2(200), --KL</cel:Column> CITY
  COUNTRY VARCHAR2(120), --MY</cel:Column> COUNTRY
  FLOORNO VARCHAR2(60), --"/> X_FLOOR
  ADDRESSYTYPE VARCHAR2(120), --High-Rise</cel:Column> ADDR_TYPE_CD
  POSTALCODE VARCHAR2(120), --57000</cel:Column> ZIPCODE
  STATE VARCHAR2(40), --WP</cel:Column> STATE
  STREETADDRESS VARCHAR2(800), --Jln Ampang</cel:Column> ADDR
  SECTION VARCHAR2(400), --"/> ADDR_LINE_2
  POBOX VARCHAR2(120), --"/> X_PO_BOX
  STREETTYPE VARCHAR2(400), --"/> X_STREET_TYPE
	UNITNO VARCHAR2(60), --187</cel:Column> X_UNIT
	CONTACTALTERNATENUM VARCHAR2(160), --CONTACT ALT_PH_NUM
	CONTACTBUSINESSPHONE VARCHAR2(160), --"/> WORK_PH_NUM
	CONTACTEMAIL VARCHAR2(1400), --psaini3@mailinator.com</cel:Column> EMAIL_ADDR
	CONTACTFIRSTNAME VARCHAR2(200), --THEVEN NAIDU</cel:Column> FST_NAME
  CONTACTHOMEPHONE VARCHAR2(160), --"/> HOME_PH_NUM
  CONTACTLASTNAME VARCHAR2(200), --">value</cel:Column> LAST_NAME
  CONTACTMOBILENUM VARCHAR2(160), --0135008478</cel:Column> CELL_PH_NUM
  CONTACTPREFERREDTIME VARCHAR2(120), -- S_CONTACT_FNX BEST_CALLTM_CD
	CONTACTTYPE VARCHAR2(120), -- CONTACT CON_CD
  CONTACTSALUTATION VARCHAR2(120), --"/> CONTACT X_PER_TITLE
  PREFERREDCONTACTMETHOD VARCHAR2(120), --">Email</cel:Column> CONTACT PREF_COMM_METH_CD
	MOBILENUMBER VARCHAR2(400), --"/> ASSET SERIAL_NUM
  PRINCIPLEMOBILENUMBER VARCHAR2(100), --"/> ASSET X_PRINCIPLE_SERV_ID
	ASSETID VARCHAR2(60), --"/> ASSET ROW_ID
  ASSETINTEGRATIONID VARCHAR2(120), --"/> ASSET INTEGRATION_ID
  SMEGROUPID VARCHAR2(200), --"/> ASSET X_SME_GROUP
  PRE_POS_INDICATOR VARCHAR2(120), --"/> S_PROD_INT PAYMNT_TYPE_CD
  PLAN VARCHAR2(400), --"/> S_PROD_INT NAME
  BILLTYPE VARCHAR2(1000), --"/> ASSET_XA CHAR_VAL ATTR_NAME=Billing Type
  PRODPROMNAME VARCHAR2(400), --"/> S_PROD_INT NAME 
  CUSTOMERSINCE DATE, --2018-04-10T00:00:00.000+08:00</cel:Column> S_ORG_EXT CUST_SINCE_DT
	CONTACTROWID VARCHAR2(60), --1-6WZMJ</cel:Column> CONTACT ROW_ID
  ASSTSTATUS VARCHAR2(120), -- S_ASSET STATUS_CD
	ASSETSUBSTATUS VARCHAR2(120), -- S_ASSET X_SUB_STATUS_CD
	PREFERREDCONTACTLANG VARCHAR2(400), -- S_CONTACT_TNTX.LANGUAGES
	FACEBOOKID VARCHAR2(400), -- S_ORG_EXT_XM.ATTRIB_01 NAME='FACEBOOK' TYPE='SOCIAL MEDIA'
	GOOGLEPLUSID VARCHAR2(400), -- 
	TWITTERID VARCHAR2(400),
	KENANNAME VARCHAR2(1000), -- S_ASSET_XA.CHAR_VAL ATTR_NAME='Name'
	BILLCYCLE NUMBER, --INV_PROF BILL_CYCLE
	GSTTAXRELIEF CHAR(4), -- X_TAX_REL_FLG
	GSTTAXRELIEFID VARCHAR2(400)); -- X_TAX_REL_ID
  
